name: dastyare_social_sh

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "9824:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
